# Generated by Django 5.1.1 on 2024-09-08 00:46

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cocktail',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('first_image', models.URLField()),
                ('bckg_image', models.URLField()),
                ('name', models.CharField(max_length=120)),
                ('description', models.JSONField()),
                ('ingredients', models.JSONField()),
                ('season', models.IntegerField(choices=[(0, 'Spring'), (1, 'Summer'), (2, 'Autumn'), (3, 'Winter')])),
                ('alcohol_lvl', models.IntegerField(choices=[(1, 'LOW'), (2, 'MID'), (3, 'HIGH')])),
                ('tags', models.JSONField()),
            ],
        ),
    ]
