# Generated by Django 5.1.1 on 2024-09-08 05:35

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_cocktail_liquor_profile_profilereviews'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cocktail_detail',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('images', models.JSONField()),
                ('name', models.CharField(max_length=120)),
                ('description', models.JSONField()),
                ('ingredients', models.JSONField()),
                ('instructions', models.JSONField()),
            ],
        ),
        migrations.RenameField(
            model_name='cocktail',
            old_name='bckg_image',
            new_name='image',
        ),
        migrations.RemoveField(
            model_name='cocktail',
            name='first_image',
        ),
        migrations.RemoveField(
            model_name='cocktail',
            name='ingredients',
        ),
    ]
