# Generated by Django 5.1.1 on 2024-09-08 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0003_cocktail_detail_rename_bckg_image_cocktail_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cocktail',
            name='season',
            field=models.IntegerField(choices=[(0, 'All Seasons'), (1, 'Spring'), (2, 'Summer'), (3, 'Autumn'), (4, 'Winter')]),
        ),
    ]
